Fix go build break because cert expired issue. (#75)
Fix go build break because cert expired issue.

Why I did it
Go build break because cert expired:

2025-02-01T01:59:48.6089594Z --- FAIL: TestVerifyConnection (0.00s)
2025-02-01T01:59:48.6089953Z --- FAIL: TestVerifyConnection/TLSv12 (0.00s)
2025-02-01T01:59:48.6090351Z handshake_client_test.go:1721: RequireAndVerifyClientCert-FullHandshake: handshake failed: remote error: tls: bad certificate
2025-02-01T01:59:48.6090819Z --- FAIL: TestVerifyConnection/TLSv13 (0.00s)
2025-02-01T01:59:48.6091221Z handshake_client_test.go:1721: RequireAndVerifyClientCert-FullHandshake: handshake failed: remote error: tls: bad certificate
2025-02-01T01:59:48.6091817Z --- FAIL: TestResumptionKeepsOCSPAndSCT (0.01s)
2025-02-01T01:59:48.6092097Z --- FAIL: TestResumptionKeepsOCSPAndSCT/TLSv12 (0.00s)
2025-02-01T01:59:48.6092425Z handshake_client_test.go:2513: handshake failed: remote error: tls: bad certificate
2025-02-01T01:59:48.6092762Z --- FAIL: TestResumptionKeepsOCSPAndSCT/TLSv13 (0.01s)
2025-02-01T01:59:48.6093096Z handshake_client_test.go:2513: handshake failed: remote error: tls: bad certificate

How I did it
Add upstream fix from here: https://go-review.googlesource.com/c/gofrontend/+/640435

How to verify it
Pass all UT.
Manually verify golang debs generated.